//Hakan ONAY 170504021
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author zeyne
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }
    University uni = new University();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDozentTC = new javax.swing.JTextField();
        jTextFieldDozentVorname = new javax.swing.JTextField();
        jTextFieldDozentNachname = new javax.swing.JTextField();
        jButtonDozentAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDozent = new javax.swing.JList<>();
        jButtonDozentEdit = new javax.swing.JButton();
        jButtonDozentDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLVAnummer = new javax.swing.JTextField();
        jTextFieldLVAname = new javax.swing.JTextField();
        jButtonLVAadd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListLVAs = new javax.swing.JList<>();
        jButtonLvaEdit = new javax.swing.JButton();
        jButtonLvaDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListLVas = new javax.swing.JList<>();
        jButtonRegisterDozent = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListDozents = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonLogOffDozent = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldStudentMatrikelNum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldStudentVorname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldStudentNachname = new javax.swing.JTextField();
        jButtonStudentAdd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListStudents = new javax.swing.JList<>();
        jButtonStudentEdit = new javax.swing.JButton();
        jButtonStudentDelete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListStudentss = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListLvas = new javax.swing.JList<>();
        jButtonStudentRegister = new javax.swing.JButton();
        jButtonStudentLogOff = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jComboBoxStudents = new javax.swing.JComboBox<>();
        jComboBoxDozents = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListStudentsLVAs = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jListDozentsLVAs = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TC Num");

        jLabel2.setText("Vorname");

        jLabel3.setText("Nachname");

        jButtonDozentAdd.setText("Add");
        jButtonDozentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDozentAddActionPerformed(evt);
            }
        });

        jListDozent.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListDozentValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListDozent);

        jButtonDozentEdit.setText("Edit");
        jButtonDozentEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDozentEditActionPerformed(evt);
            }
        });

        jButtonDozentDelete.setText("Delete");
        jButtonDozentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDozentDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDozentTC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDozentVorname, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDozentNachname, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDozentAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jButtonDozentEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDozentDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDozentAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDozentEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDozentDelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldDozentTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDozentVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDozentNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(116, 116, 116))
        );

        jTabbedPane1.addTab("Add Dozent", jPanel1);

        jLabel4.setText("LVA Nummer");

        jLabel5.setText("LVA Name");

        jButtonLVAadd.setText("Add");
        jButtonLVAadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLVAaddActionPerformed(evt);
            }
        });

        jListLVAs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListLVAsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListLVAs);

        jButtonLvaEdit.setText("Edit");
        jButtonLvaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLvaEditActionPerformed(evt);
            }
        });

        jButtonLvaDelete.setText("Delete");
        jButtonLvaDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLvaDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldLVAname, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTextFieldLVAnummer))
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLvaDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLvaEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLVAadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldLVAnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLVAadd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldLVAname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonLvaEdit)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLvaDelete))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("Add LVA", jPanel2);

        jScrollPane4.setViewportView(jListLVas);

        jButtonRegisterDozent.setText("Register");
        jButtonRegisterDozent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterDozentActionPerformed(evt);
            }
        });

        jListDozents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(jListDozents);

        jLabel7.setText("Dozents");

        jLabel8.setText("LVAs");

        jButtonLogOffDozent.setText("Log Off");
        jButtonLogOffDozent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOffDozentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonRegisterDozent)))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLogOffDozent)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(278, 278, 278))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegisterDozent)
                    .addComponent(jButtonLogOffDozent))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Assign Dozent", jPanel3);

        jLabel9.setText("Matrikelnum");

        jLabel10.setText("Vorname");

        jLabel11.setText("Nachname");

        jButtonStudentAdd.setText("Add");
        jButtonStudentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentAddActionPerformed(evt);
            }
        });

        jListStudents.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListStudentsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListStudents);

        jButtonStudentEdit.setText("Edit");
        jButtonStudentEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentEditActionPerformed(evt);
            }
        });

        jButtonStudentDelete.setText("Delete");
        jButtonStudentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldStudentMatrikelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStudentVorname, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStudentNachname, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonStudentAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addComponent(jButtonStudentEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonStudentDelete))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonStudentAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonStudentEdit)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonStudentDelete))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldStudentMatrikelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldStudentVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStudentNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Add Student", jPanel4);

        jLabel12.setText("Students");

        jListStudentss.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(jListStudentss);

        jLabel13.setText("LVAs");

        jScrollPane7.setViewportView(jListLvas);

        jButtonStudentRegister.setText("Register");
        jButtonStudentRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentRegisterActionPerformed(evt);
            }
        });

        jButtonStudentLogOff.setText("Log Off");
        jButtonStudentLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentLogOffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonStudentRegister)))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStudentLogOff)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(278, 278, 278))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStudentRegister)
                    .addComponent(jButtonStudentLogOff))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Add Student's LVA", jPanel5);

        jComboBoxStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStudentsActionPerformed(evt);
            }
        });

        jComboBoxDozents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDozentsActionPerformed(evt);
            }
        });

        jListStudentsLVAs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane8.setViewportView(jListStudentsLVAs);

        jListDozentsLVAs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane9.setViewportView(jListDozentsLVAs);

        jLabel6.setText("Students");

        jLabel14.setText("Dozents");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDozents, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDozents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("List All", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDozentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDozentAddActionPerformed
        DefaultListModel DozentModel = new DefaultListModel();
        DefaultComboBoxModel DozentBoxModel = new DefaultComboBoxModel();
        long testtc = Long.parseLong(jTextFieldDozentTC.getText());
        long maintc = Dozent.controlTc(testtc);
        //Controlling whether the TC Number is 11 digits.
        String dozentname = jTextFieldDozentVorname.getText();
        String dozentnachname = jTextFieldDozentNachname.getText();
        if (maintc == testtc) {
            Dozent dozent = new Dozent(maintc);
            if (uni.searchDozent(maintc) == null) {
                uni.addDozent(dozentname, dozentnachname, maintc);
            } else {
                JOptionPane.showMessageDialog(rootPane, "This dozent is already in the system.");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "False input for TC Nummer");
        }
        for (Dozent dozent : uni.getDozentList()) {
            DozentModel.addElement(dozent);
            DozentBoxModel.addElement(dozent);
        }
        jListDozent.setModel(DozentModel);
        jListDozents.setModel(DozentModel);
        jComboBoxDozents.setModel(DozentBoxModel);
    }//GEN-LAST:event_jButtonDozentAddActionPerformed

    private void jButtonStudentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentAddActionPerformed
        DefaultListModel StuModel = new DefaultListModel();
        DefaultComboBoxModel StudentBoxModel = new DefaultComboBoxModel();
        int testid = Integer.parseInt(jTextFieldStudentMatrikelNum.getText());
        int id = 0;
        String vorname = jTextFieldStudentVorname.getText();
        String nachname = jTextFieldStudentNachname.getText();
        //vorname == name
        //nachname == surname

        int testidlength = String.valueOf(testid).length();
        //It must have a length of 7 so we are testing it
        if ((testidlength == 7) && (testid != 0)) {

            id = testid;
            Student mainstud = new Student(id);

            if (uni.searchStudent(id) == null) {
                uni.addStudent(id, vorname, nachname);

            } else {
                JOptionPane.showMessageDialog(rootPane, "This student is already in the system.");

            }

        } else {

            JOptionPane.showMessageDialog(rootPane, "False input for Student Number.");
        }
        // Program can add Students only with Studentnumber
        //Name and Surname are additional.
        for (Student student : uni.getList()) {
            StuModel.addElement(student);
            StudentBoxModel.addElement(student);
        }
        jListStudents.setModel(StuModel);
        jListStudentss.setModel(StuModel);
        jComboBoxStudents.setModel(StudentBoxModel);

    }//GEN-LAST:event_jButtonStudentAddActionPerformed

    private void jButtonLVAaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLVAaddActionPerformed
        DefaultListModel LvaModel = new DefaultListModel();
        String mainLVAname = jTextFieldLVAname.getText();

        System.out.println("Lesson Surname :");
        int mainLVAnummer = Integer.parseInt(jTextFieldLVAnummer.getText());

        String LVAcode = LVA.controlLVA(mainLVAname, mainLVAnummer);
        //Controlling the Lesson name, it must be given as : INF101 Or MAT204 etc
        if (LVAcode == "null") {
            JOptionPane.showMessageDialog(rootPane, "False Input for Lesson");
        } else {
            if (uni.searchLVA(LVAcode) == null) {
                uni.addLVA(mainLVAname, mainLVAnummer);
            } else {
                JOptionPane.showMessageDialog(rootPane, "This lva is already in the system.");
            }

        }
        for (LVA lva : uni.getLVAList()) {
            LvaModel.addElement(lva);
        }
        jListLVAs.setModel(LvaModel);
        jListLVas.setModel(LvaModel);
        jListLvas.setModel(LvaModel);
    }//GEN-LAST:event_jButtonLVAaddActionPerformed

    private void jButtonRegisterDozentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterDozentActionPerformed

        Object SelectedDozent = jListDozents.getSelectedValue();
        Object SelectedLVA = jListLVas.getSelectedValue();
        for (Dozent dozent : uni.getDozentList()) {
            if (dozent.equals(SelectedDozent)) {
                for (LVA lva : uni.getLVAList()) {
                    if (lva.toString().equals(SelectedLVA.toString())) {
                        String lvaCode = lva.getLVACode();
                        dozent.LVAassign(lvaCode);
                        lva.addDozentTC(dozent.getTc());
                    }
                }
            }
        }

    }//GEN-LAST:event_jButtonRegisterDozentActionPerformed

    private void jButtonLogOffDozentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOffDozentActionPerformed
        Object SelectedDozent = jListDozents.getSelectedValue();
        Object SelectedLVA = jListLVas.getSelectedValue();
        for (Dozent dozent : uni.getDozentList()) {
            if (dozent.equals(SelectedDozent)) {
                for (LVA lva : uni.getLVAList()) {
                    if (lva.toString().equals(SelectedLVA.toString())) {
                        String lvaCode = lva.getLVACode();
                        dozent.LVAunassign(lvaCode);
                        lva.tcRemove(dozent.getTc());
                        break;
                    }
                }
            }

        }
    }//GEN-LAST:event_jButtonLogOffDozentActionPerformed

    private void jButtonStudentRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentRegisterActionPerformed
        Object SelectedStudent = jListStudentss.getSelectedValue();
        Object SelectedLVA = jListLvas.getSelectedValue();
        for (Student student : uni.getList()) {
            if (student.equals(SelectedStudent)) {
                for (LVA lva : uni.getLVAList()) {
                    if (lva.equals(SelectedLVA)) {
                        String lvaCode = lva.getLVACode();
                        student.LVAanmelden(lvaCode);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonStudentRegisterActionPerformed

    private void jButtonStudentLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentLogOffActionPerformed
        Object SelectedStudent = jListStudentss.getSelectedValue();
        Object SelectedLVA = jListLvas.getSelectedValue();
        for (Student student : uni.getList()) {
            if (student.equals(SelectedStudent)) {
                for (LVA lva : uni.getLVAList()) {
                    if (lva.equals(SelectedLVA)) {
                        String lvaCode = lva.getLVACode();
                        student.LVAabmelden(lvaCode);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonStudentLogOffActionPerformed

    private void jComboBoxDozentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDozentsActionPerformed
        String SelectedDozent = jComboBoxDozents.getSelectedItem().toString();
        DefaultListModel DozentModel = new DefaultListModel();
        for (Dozent dozent : uni.getDozentList()) {
            if (dozent.toString().equals(SelectedDozent)) {
                for (String lva : dozent.getAssigned()) {
                    DozentModel.addElement(lva);
                }
            }
        }
        jListDozentsLVAs.setModel(DozentModel);
    }//GEN-LAST:event_jComboBoxDozentsActionPerformed

    private void jComboBoxStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStudentsActionPerformed
        String SelectedStudent = jComboBoxStudents.getSelectedItem().toString();
        DefaultListModel StudentModel = new DefaultListModel();
        for (Student student : uni.getList()) {
            if (student.toString().equals(SelectedStudent)) {
                for (String lva : student.getAngemeldet()) {
                    StudentModel.addElement(lva);
                }
            }
        }
        jListStudentsLVAs.setModel(StudentModel);
    }//GEN-LAST:event_jComboBoxStudentsActionPerformed

    private void jListDozentValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListDozentValueChanged
        Object SelectedDozent = jListDozent.getSelectedValue();
        for (Dozent dozent : uni.getDozentList()) {
            if (dozent.equals(SelectedDozent)) {
                jTextFieldDozentTC.setText(String.valueOf(dozent.getTc()));
                jTextFieldDozentNachname.setText(dozent.getNachName());
                jTextFieldDozentVorname.setText(dozent.getVorName());
            }
        }


    }//GEN-LAST:event_jListDozentValueChanged

    private void jButtonDozentEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDozentEditActionPerformed
        DefaultListModel DozentModel = new DefaultListModel();
        DefaultComboBoxModel DozentBoxModel = new DefaultComboBoxModel();
        Object SelectedDozent = jListDozent.getSelectedValue();
        for (Dozent dozent : uni.getDozentList()) {
            if (dozent.equals(SelectedDozent)) {
                dozent.setTc(Long.parseLong(jTextFieldDozentTC.getText()));
                dozent.setNachName(jTextFieldDozentNachname.getText());
                dozent.setVorName(jTextFieldDozentVorname.getText());
            }
        }
        for (Dozent dozent : uni.getDozentList()) {
            DozentModel.addElement(dozent);
            DozentBoxModel.addElement(dozent);
        }
        jListDozent.setModel(DozentModel);
        jListDozents.setModel(DozentModel);
        jComboBoxDozents.setModel(DozentBoxModel);
    }//GEN-LAST:event_jButtonDozentEditActionPerformed

    private void jButtonLvaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLvaEditActionPerformed
        DefaultListModel LvaModel = new DefaultListModel();
        Object SelectedLva = jListLVAs.getSelectedValue();
        LVA.controlLVA(jTextFieldLVAname.getText(), Integer.parseInt(jTextFieldLVAnummer.getText()));
        for (LVA lva : uni.getLVAList()) {
            if (lva.equals(SelectedLva)) {
                lva.setLVAName(jTextFieldLVAname.getText());
                lva.setLVANummer(Integer.parseInt(jTextFieldLVAnummer.getText()));
                lva.setLvacode(jTextFieldLVAname.getText()+jTextFieldLVAnummer.getText());
            }
        }

        for (LVA lva : uni.getLVAList()) {
            LvaModel.addElement(lva);
        }
        jListLVAs.setModel(LvaModel);
        jListLVas.setModel(LvaModel);
        jListLvas.setModel(LvaModel);

    }//GEN-LAST:event_jButtonLvaEditActionPerformed

    private void jListLVAsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListLVAsValueChanged
        Object SelectedLva = jListLVAs.getSelectedValue();
        for (LVA lva : uni.getLVAList()) {
            if (lva.equals(SelectedLva)) {
                jTextFieldLVAname.setText(lva.getLVAName());
                jTextFieldLVAnummer.setText(String.valueOf(lva.getLVANummer()));
            }
        }
    }//GEN-LAST:event_jListLVAsValueChanged

    private void jButtonDozentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDozentDeleteActionPerformed
        DefaultListModel DozentModel = new DefaultListModel();
        DefaultComboBoxModel DozentBoxModel = new DefaultComboBoxModel();
        uni.deleteDozent(jTextFieldDozentVorname.getText(), jTextFieldDozentNachname.getText());
        for (Dozent dozent : uni.getDozentList()) {
            DozentModel.addElement(dozent);
            DozentBoxModel.addElement(dozent);
        }
        jListDozent.setModel(DozentModel);
        jListDozents.setModel(DozentModel);
        jComboBoxDozents.setModel(DozentBoxModel);
    }//GEN-LAST:event_jButtonDozentDeleteActionPerformed

    private void jButtonLvaDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLvaDeleteActionPerformed
        DefaultListModel LvaModel = new DefaultListModel();
        uni.deleteLVA(jTextFieldLVAname.getText()+jTextFieldLVAnummer.getText());
        for (LVA lva : uni.getLVAList()) {
            LvaModel.addElement(lva);
        }
        jListLVAs.setModel(LvaModel);
        jListLVas.setModel(LvaModel);
        jListLvas.setModel(LvaModel);

    }//GEN-LAST:event_jButtonLvaDeleteActionPerformed

    private void jButtonStudentEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentEditActionPerformed
        DefaultListModel StudentModel = new DefaultListModel();
        DefaultComboBoxModel StudentBoxModel = new DefaultComboBoxModel();
        Object SelectedStudent = jListStudents.getSelectedValue();
        for (Student student : uni.getList()) {
            if (student.equals(SelectedStudent)) {
                student.setMatrikel(Integer.parseInt(jTextFieldStudentMatrikelNum.getText()));
                student.setNachname(jTextFieldStudentNachname.getText());
                student.setVorname(jTextFieldStudentVorname.getText());
            }
        }
        for (Student student : uni.getList()) {
            StudentModel.addElement(student);
            StudentBoxModel.addElement(student);
        }
        jListStudents.setModel(StudentModel);
        jListStudentss.setModel(StudentModel);
        jComboBoxStudents.setModel(StudentBoxModel);
    }//GEN-LAST:event_jButtonStudentEditActionPerformed

    private void jButtonStudentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentDeleteActionPerformed
        DefaultListModel StudentModel = new DefaultListModel();
        DefaultComboBoxModel StudentBoxModel = new DefaultComboBoxModel();
        uni.deleteStudent(Integer.parseInt(jTextFieldStudentMatrikelNum.getText()));
        for (Student student : uni.getList()) {
            StudentModel.addElement(student);
            StudentBoxModel.addElement(student);
        }
        jListStudents.setModel(StudentModel);
        jListStudentss.setModel(StudentModel);
        jComboBoxStudents.setModel(StudentBoxModel);
    }//GEN-LAST:event_jButtonStudentDeleteActionPerformed

    private void jListStudentsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListStudentsValueChanged
        Object SelectedStudent = jListStudents.getSelectedValue();
        for (Student student : uni.getList()) {
            if (student.equals(SelectedStudent)) {
                jTextFieldStudentMatrikelNum.setText(String.valueOf(student.getMatrikel()));
                jTextFieldStudentNachname.setText(student.getNachname());
                jTextFieldStudentVorname.setText(student.getVorname());
            }
        }
    }//GEN-LAST:event_jListStudentsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDozentAdd;
    private javax.swing.JButton jButtonDozentDelete;
    private javax.swing.JButton jButtonDozentEdit;
    private javax.swing.JButton jButtonLVAadd;
    private javax.swing.JButton jButtonLogOffDozent;
    private javax.swing.JButton jButtonLvaDelete;
    private javax.swing.JButton jButtonLvaEdit;
    private javax.swing.JButton jButtonRegisterDozent;
    private javax.swing.JButton jButtonStudentAdd;
    private javax.swing.JButton jButtonStudentDelete;
    private javax.swing.JButton jButtonStudentEdit;
    private javax.swing.JButton jButtonStudentLogOff;
    private javax.swing.JButton jButtonStudentRegister;
    private javax.swing.JComboBox<String> jComboBoxDozents;
    private javax.swing.JComboBox<String> jComboBoxStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListDozent;
    private javax.swing.JList<String> jListDozents;
    private javax.swing.JList<String> jListDozentsLVAs;
    private javax.swing.JList<String> jListLVAs;
    private javax.swing.JList<String> jListLVas;
    private javax.swing.JList<String> jListLvas;
    private javax.swing.JList<String> jListStudents;
    private javax.swing.JList<String> jListStudentsLVAs;
    private javax.swing.JList<String> jListStudentss;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldDozentNachname;
    private javax.swing.JTextField jTextFieldDozentTC;
    private javax.swing.JTextField jTextFieldDozentVorname;
    private javax.swing.JTextField jTextFieldLVAname;
    private javax.swing.JTextField jTextFieldLVAnummer;
    private javax.swing.JTextField jTextFieldStudentMatrikelNum;
    private javax.swing.JTextField jTextFieldStudentNachname;
    private javax.swing.JTextField jTextFieldStudentVorname;
    // End of variables declaration//GEN-END:variables
}
